import numpy as np
print(np.zeros((5)))
a = np .array([[1,2,3],[4,5,6]])
print(np.full((2,3),4))
print(np.full_like(a,4))
print(np.full(a.shape,4))
print(np.random.random_sample(a.shape))
print(np.random.randint(4,17,size=(2,2)))
print(np.identity(3))
arr = np.array([1,2,3])
r1 = np.repeat(arr,2)
r2 = np.repeat(a,2,axis=0)
r3 = np.repeat(a,2,axis=1)
print(r1)
print(r2)
print(r3)
